### PR TITLE
Clean dracut log

### PR DESCRIPTION
**Pull request by melissawen**
Set DRACUT_NO_XATTR env var to suppress not relevant warnings in the log

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
@melissawen, any update here?

**Comment by rodrigosiqueira** [comment]
@melissawen any update?

**Comment by melissawen** [comment]
BTW, the two logs are attached to check differences
[dracut_NO_XATTR_log.txt](https://github.com/kworkflow/kworkflow/files/10207697/dracut_NO_XATTR_log.txt)
[dracut_original_log.txt](https://github.com/kworkflow/kworkflow/files/10207698/dracut_original_log.txt)

**Comment by rodrigosiqueira** [comment]
Thanks a lot! Merged into the unstable branch.

**Pull request closed without merging**
