### PR TITLE
Separate build config from base kw config

### PR DESCRIPTION
**Pull request by isinyaaa**
This is a change requested by @rodrigosiqueira in PR #543 that was quite large, so I preferred to split it. Note: this is based on #615.

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
Hi @isinyaaa ,
I recently created `etc/init_templates/` where I maintain all the default configs. Please, update your change to put the new build files template in that folder. Do not forget to update `kw init` as well.

**Comment by rodrigosiqueira** [comment]
@isinyaaa could you check the unit test failure?

**Comment by kwy95** [comment]
It seems that the `kworkflow_template.config` is not where the `setup.sh` file expects it to be, that's why the CI is failing.

**Comment by isinyaaa** [comment]
I still have some minor things to add here, but can you please review it as is?

**Comment by rodrigosiqueira** [comment]
I fixed the issue that I mentioned before and merged this change in the unstable branch. Thanks.

**Pull request closed without merging**
