### PR TITLE
sounds: Add new notification sounds to kw

### PR DESCRIPTION
**Pull request by joaoseckler**
This commit introduces six new sounds to kw, and removes the old one,
for it's lack of licensing. It also adds a page to the documentation
with credits to the authors of the sounds, changes the default sound
notification in etc/kworkflow_template.config and adjust tests
accordingly.

Closes: #317 and #333

Signed-off-by: João Seckler <jseckler@riseup.net>

### CODE REVIEW

**Comment by joaoseckler** [comment]
I would like feedback specifically for these aspects of this PR:

- Where should we put the `sound_attribution.rst` file? I thought maybe a new section "credits" could exist.
- Is that the best name for it? "Sound attributions?" I was inspired by minecraft's analogous page: [https://www.minecraft.net/en-us/attribution/sound](https://www.minecraft.net/en-us/attribution/sound)
- Most importantly: are the sounds good? Do they notify? Do they overcome some music that a user might be listening? Is it clipping?

Thanks a lot!

**Comment by alan-barzilay** [comment]
> Where should we put the sound_attribution.rst file? I thought maybe a new section "credits" could exist.

Since sounds are the only thing we need to attribute credit for at the moment I think it would make sense to just leave it inside the `sounds` directory, this way it is also closer to the file being attributed

**Comment by joaoseckler** [comment]
> > Where should we put the sound_attribution.rst file? I thought maybe a new section "credits" could exist.
> 
> Since sounds are the only thing we need to attribute credit for at the moment I think it would make sense to just leave it inside the `sounds` directory, this way it is also closer to the file being attributed

And then keep it as a plain text file instead of rst, right? Makes sense to me. At the same time, shouldn't this be inside of kw's documentation?

**Comment by rodrigosiqueira** [comment]
> > > Where should we put the sound_attribution.rst file? I thought maybe a new section "credits" could exist.
> > 
> > 
> > Since sounds are the only thing we need to attribute credit for at the moment I think it would make sense to just leave it inside the `sounds` directory, this way it is also closer to the file being attributed
> 
> And then keep it as a plain text file instead of rst, right? Makes sense to me. At the same time, shouldn't this be inside of kw's documentation?

I think the plain text should be enough.

**Comment by rodrigosiqueira** [comment]
Most of the sounds are hard to hear when we are playing some music. For example, try to hear them while playing this music:

https://youtu.be/ohJxNSn9aL0?t=1526

Also, `ovo.wav` is really hard to hear. I think we can remove it.

Can you try to make these sounds a little bit louder?
P.s.: `bell.wav` is the best one in terms of volume.

**Comment by joaoseckler** [comment]
Felipe Kouznets has helped me louden these sounds more. At this point, if my volume is at 100%, my ears hurt a little bit when listening to these sounds. I don't know if that should be a concern.

I also removed "ovo.wav"

**Comment by magalilemes** [comment]
I like all the sounds. They're at a good volume level and not clipping, but I believe the caixa one is a bit too short and abrupt.

**Comment by joaoseckler** [comment]
> I like all the sounds. They're at a good volume level and not clipping, but I believe the caixa one is a bit too short and abrupt.

Do you think we should delete it? I think I can see myself using it

**Comment by alan-barzilay** [comment]
>    > I like all the sounds. They're at a good volume level and not clipping, but I believe the caixa one is a bit too short and abrupt.
> 
> Do you think we should delete it? I think I can see myself using it


I think we should keep it, since its not the default I see no problem

**Comment by rodrigosiqueira** [comment]
bell.wav and berimbau.wav are my favorite :)
I would make `bell.wav` the default one.

@melissawen any comment here?

**Comment by rodrigosiqueira** [comment]
@joaoseckler did you try to add the fade-in effect at the begging of each sound?

**Comment by joaoseckler** [comment]
@rodrigosiqueira Fade-in effects added!

**Review by rodrigosiqueira — CHANGES_REQUESTED** [review]
Hi @joaoseckler ,

Final change:
Add a rule in the setup that creates a symbolic link from complete.wav to bell.wav. Users with the old `kworkflow.config` still have `complete.wav` in their config file, which does not exist after your patch; the symbolic link will ensure that old config files will still work.

**Review by kwy95 — APPROVED** [review]
LGTM

**Comment by rodrigosiqueira** [comment]
@joaoseckler did you see my previous comment?

**Comment by rodrigosiqueira** [comment]
Merged, thanks

**Pull request closed without merging**
