### PR TITLE
src: maintainers: Modernize maintainers

### LINKED ISSUE #456: Modernize maintainers
The `maintainers` feature is old and outdated, lets:

* Use the new parser system
* Use a better way to display data
* Update and expand unit tests

### PR DESCRIPTION
**Pull request by hilookas**
This commit replaces old parser with new `kw_parse`, updates maintainers entrypoint to `maintainers_main` and updates relevant tests.

Closes #456

Signed-off-by: Haiqin Cui <i@18kas.com>

### CODE REVIEW

**Comment by hilookas** [comment]
This commit is similar to pull #679.

**Review by rodrigosiqueira — COMMENTED** [review]
Almost there, let's just rename this file and the test file to `maintainers`

**Comment by hilookas** [comment]
That's what I thought too. I'll change the name right away. :D

**Comment by rodrigosiqueira** [comment]
Merged! Thanks!

**Pull request closed without merging**
