### PR TITLE
Reestructure tests folder

### PR DESCRIPTION
**Pull request by uwla**
This PR:

- moves unit tests to tests/unit
- adds option to specify unit or global tests in run_tests.sh via the flags --unit,-u/--integration,-i

The motivation behind it is to make the test folder structure more organized and prepare the environment for the integration tests by making it easier and cleaner where to put them.

It is related to PR #953.

I decided to create a separated PR due to the followign reasons:

- it is easier to review separated PRs
- the other PR kinda depends on the changes implemented here
- incorporating this PR into the unstable branch will simplify things in the other PR
- we can move faster by splitting the work

It is important to notice that several files were changed, but the changes are merely updating file paths:

- `tests/utils.sh` -> `tests/unit/utils.sh`
- `tests/samples` -> `tests/unit/samples`
- `tests/checkpatch_wrapper.sh` -> `tests/unit/checkpatch_wrapper.sh`
- and more

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
@uwla could you rebase this change?

**Comment by uwla** [comment]
> @uwla could you rebase this change?

Surely!

**Comment by uwla** [comment]
@rodrigosiqueira I think I've done it.
There are not conflict anymore and the PR branch is synced with the official unstable branch.

**Comment by rodrigosiqueira** [comment]
Merged, thanks

**Pull request closed without merging**
