### PR TITLE
Added --repeat to pomodoro

### PR DESCRIPTION
**Pull request by Vighnesh-Patidar**
Now previous pomodoro session can be repeated by just kw pomodoro --repeat.

### CODE REVIEW

**Comment by davidbtadokoro** [comment]
Hi @Vighnesh-Patidar, and thank you for your first PR! Sorry for the delayed answer :disappointed: 

First of all, as you are a starter, there are some procedures and rules to the project that you still don't know (and aren't supposed to). So keep in mind that the reviewing process entails a back-and-forth important to maintain the quality of the project.

In kw, the development happens on top of the unstable branch, while the master branch is the "stable" release of the project that gets updated once in a while (this process is described [here](https://kworkflow.org/content/howtocontribute.html#development-cycle-and-branches)). You have developed on top of the master branch, so you must rebase it against the unstable branch. Also, as a general rule for any project, always create a dedicated branch for a Pull-Request (notice that you developed on top of the master branch **and** in your local master branch). To help you, here are the steps to complete the task:

1. Go to your master branch
2. Use `git checkout -b <name-of-branch-for-this-PR>` to create a dedicated branch for this change
3. Use `git switch master` and `git reset --hard HEAD~<number-of-commits-of-this-PR>` to revert your local master branch to the correct state.
4. Use `git switch <name-of-branch-for-this-PR>` and `git rebase unstable` to trigger the rebasing process (you'll probably need to solve merge conflicts).
4.1. If you don't have a local unstable branch, use `git switch unstable` before the above (and don't forget to update the unstable branch with the upstream!).

Before executing these actions, it is important to understand exactly what they do (if in doubt, revert to the git documentation).

After doing this, you will need to open a new PR because you developed on top of the master branch (usually, we just update the PR using `git rebase --interactive` and `git pull --force`).

**Comment by Vighnesh-Patidar** [comment]
Thanks for the help. I apologise for the trouble. I'll keep the details in mind next time I register a PR. I will write a new pull request with the necessary changes this day.

**Comment by rodrigosiqueira** [comment]
@Vighnesh-Patidar  you don't need to open a new PR, just update this one. You can update it by using `git push -f origin BRANCH_NAME`.

**Comment by davidbtadokoro** [comment]
> @Vighnesh-Patidar  you don't need to open a new PR, just update this one. You can update it by using `git push -f origin BRANCH_NAME`.

True. Sorry for the mess on my end

**Comment by davidbtadokoro** [comment]
@Vighnesh-Patidar any update here?

**Comment by Vighnesh-Patidar** [comment]
I thought this was good to go so I began looking out for bugs in patch-hub. I 
apologise for the oversight, I am gonna correct it now.
thanks a lot
Sorry

Vighnesh Patidar

On 2024-03-22 21:46, David de Barros Tadokoro wrote:

> @Vighnesh-Patidar [1] any update here?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/Vighnesh-Patidar
[2] https://github.com/kworkflow/kworkflow/pull/1046#issuecomment-2015437398
[3]

**Pull request closed without merging**
