### PR TITLE
tests: refactor run_tests and integration tests

### PR DESCRIPTION
**Pull request by uwla**
- move global variable declarations to top of the file
- replace `if/elif/else` blocks with `case` statement
- extract long blocks of code to their own functions
- encapsulate podman commands in library functions

This refactor does not "refactor" everything, but just a few things.

It does not:
- rename variables for more clarity
- improve comments
- reorder lines
- improve general readbility

This refactoring is NOT a duplicate of #1021 because its scope is different: it changes things that PR does not change, and it does not changes things that PR changes.

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
Hi @uwla , overall, your change lgtm. The only thing I disagree with is the replacement of `fail` with `complain` in the tests. `fail` is part of the shunit framework, and I think it makes more send in the test part.

**Comment by uwla** [comment]
Done.

**Comment by rodrigosiqueira** [comment]
Hi @uwla , it looks like this PR has conflicts. Could you rebase it against the latest unstable branch?
Thanks

**Comment by uwla** [comment]
sure

**Comment by davidbtadokoro** [comment]
Hey @uwla, any update here?

**Comment by davidbtadokoro** [comment]
Thanks for also resolving the conflicts here @uwla. I took the opportunity to skim through the change and I have two observations:

1. Maybe we can split this commit into two: one for the refactors in `run_tests.sh` and the other for the ones in `tests/integration/utils.sh`.
2. I think this PR and #1019 conflict because both define `teardown_container_environment`. However I don't think it will be a difficult conflict to resolve and we should worry about it when the first is merged into the unstable.

**Comment by rodrigosiqueira** [comment]
@uwla, from David's comment, maybe remove the container function that you added here that is already in PR #1019 .

**Comment by uwla** [comment]
ok, I'll do it in a few days

**Comment by uwla** [comment]
I'll go back to this PR after #1019 has been merged, because it introduces a new command and modifies utils used by integration tests. This PR needs to be build on top of that, in order for the code to be coeherent after merged.

**Comment by davidbtadokoro** [comment]
> I'll go back to this PR after #1019 has been merged, because it introduces a new command and modifies utils used by integration tests. This PR needs to be build on top of that, in order for the code to be coeherent after merged.

For sure, it makes sense.

**Comment by uwla** [comment]
@rodrigosiqueira I believe it should be good by now.

**Comment by davidbtadokoro** [comment]
Hi @uwla, and sorry for the delay on our end. The PR is legit IMHO, but you didn't split the commit into two like I asked in my previous comment. Because you are refactoring two files in isolated contexts, as one refactor does not depend on the other, it is best practice to make them more atomic (notice that in the commit message you say `refactor run_tests.sh, tests/integration/utils.sh`, which means that this commit is doing two things at the same time).

Nevertheless, as we took too much time for feedback, I did the split myself. Don't worry, didn't altered the code, neither your credits or the authorship. Besides the split, I added more context to the commit messages. Anyway, thanks a lot! Merged into the unstable branch :+1:

**Pull request closed without merging**
