### PR TITLE
src: bash_autocompletion: add missing completion options

### LINKED ISSUE #810: Update Bash and Zsh completions for kw
**Description:**

We need to update the Bash and Zsh completions system for kw, as there are some options like `kw build --full-cleanup` and a feature (`kw upstream-patches-ui`) that are not covered by those systems.

**Why:**

We should solve this asap, to not let it grow to far as it is really simple.

### PR DESCRIPTION
**Pull request by GuilhermeMoreno**
Some options are missing from the bash autocompletion script. In this context, add the missing options.
    
Closes #810.

### CODE REVIEW

**Review by davidbtadokoro — CHANGES_REQUESTED** [review]
Hey @joaag and @GuilhermeMoreno. Really grateful for the effort put on closing #810!

I have two points that I want you to address that can't be added as inline comments, so pay attention to the following:
1. Think you guys didn't cover it all to close the issue. In respect to the `--help` option in the Bash completions, you forgot to add it for some commands like `kernel-config-manager`. Also, if you want to add `--help` completions for all commands, you shouldn't forget to implement it for Zsh too (in `src/_kw`). Admittedly, the Zsh completion system is awful to work with (although REALLY powerful), so I will add a diff that is an example of adding `--help` to some command. At last, the issue talks about missed options like the one fixed by commit d03644e, so, double check if there aren't any cases like that (this may be laborious);
2. Just to maintain project conventions, in the commit message you should enforce the 72 char limit per line in the body. Also, remove the `Co-authored-by: Guilherme Moreno <guilhermewr9@gmail.com>` line and the blank line before the `Signed-off-by` line.

**Comment by davidbtadokoro** [comment]
Below is the diff to add Zsh completions for the `--help` option of `kw build`.

```
diff --git a/src/_kw b/src/_kw
index 3a47db1..f86cb58 100644
--- a/src/_kw
+++ b/src/_kw
@@ -92,18 +92,19 @@ _kw_b() { _kw_build }
 _kw_build()
 {
   _arguments : \
-    '(--verbose)--verbose[enable verbose mode]' \
-    '(-i --info -c --clean -f --full-cleanup -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags)'{-i,--info}'[display kernel release name, version and number of modules to compile]' \
-    '(-c --clean -f --full-cleanup -i --info -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags)'{-c,--clean}'[remove files generated by the kernel build system]' \
-    '(-f --full-cleanup -c --clean -i --info -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags)'{-f,--full-cleanup}'[reset the kernel tree to its default option integrated into env]' \
-    '(-n --menu -i --info -c --clean -f --full-cleanup -d --doc --cflags)'{-n,--menu}'[invoke kernel menuconfig]' \
-    '(-d --doc -i --info -c --clean -f --full-cleanup -n --menu --cflags)'{-d,--doc}'[build the kernel-doc]' \
-    '(-i --info -c --clean -f --full-cleanup --cflags)--ccache[enable ccache during compilation tasks]' \
-    '(-w --warnings -i --info -c --clean -f --full-cleanup --cflags)'{-w,--warnings}'[enable compilation warnings]:log level:(1 2 3 12 13 23 123)' \
-    '(-S --cpu-scaling -i --info -c --clean -f --full-cleanup --cflags)'{-S,--cpu-scaling}'[set CPU usage]:scaling percentage: ' \
-    '(-s --save-log-to -i --info -c --clean -f --full-cleanup --cflags)'{-s,--save-log-to}'[save full compilation log with the enabled warnings to the specified path]:log path:_files' \
-    '(-i --info -c --clean -f --full-cleanup --cflags)--llvm[enable the usage of the LLVM toolchain]' \
-    '(-i --info -c --clean -f --full-cleanup -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags)--cflags[customize kernel compilation with specific flags]'
+    '(--help -i --info -c --clean -f --full-cleanup -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags --verbose)--help[display man page for kw build]' \
+    '(--verbose --help)--verbose[enable verbose mode]' \
+    '(-i --info -c --clean -f --full-cleanup -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags --help)'{-i,--info}'[display kernel release name, version and number of modules to compile]' \
+    '(-c --clean -f --full-cleanup -i --info -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags --help)'{-c,--clean}'[remove files generated by the kernel build system]' \
+    '(-f --full-cleanup -c --clean -i --info -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags --help)'{-f,--full-cleanup}'[reset the kernel tree to its default option integrated into env]' \
+    '(-n --menu -i --info -c --clean -f --full-cleanup -d --doc --cflags --help)'{-n,--menu}'[invoke kernel menuconfig]' \
+    '(-d --doc -i --info -c --clean -f --full-cleanup -n --menu --cflags --help)'{-d,--doc}'[build the kernel-doc]' \
+    '(-i --info -c --clean -f --full-cleanup --cflags --help)--ccache[enable ccache during compilation tasks]' \
+    '(-w --warnings -i --info -c --clean -f --full-cleanup --cflags --help)'{-w,--warnings}'[enable compilation warnings]:log level:(1 2 3 12 13 23 123)' \
+    '(-S --cpu-scaling -i --info -c --clean -f --full-cleanup --cflags --help)'{-S,--cpu-scaling}'[set CPU usage]:scaling percentage: ' \
+    '(-s --save-log-to -i --info -c --clean -f --full-cleanup --cflags --help)'{-s,--save-log-to}'[save full compilation log with the enabled warnings to the specified path]:log path:_files' \
+    '(-i --info -c --clean -f --full-cleanup --cflags --help)--llvm[enable the usage of the LLVM toolchain]' \
+    '(-i --info -c --clean -f --full-cleanup -n --menu -d --doc --ccache -w --warnings -S --cpu-scaling -s --save-log-to --llvm --cflags --help)--cflags[customize kerne
l compilation with specific flags]'
 
 }
```

What I'm doing here is making sure that `--help` is mutually exclusive to every other option of `kw build`. Although we try to keep kw robust to ignore any other option passed with `--help` (`kw build --help --menu` ignores `--menu`) we shouldn't display something to the user that isn't possible. As said, Zsh completions are awful, and the way to make this mutual exclusion is to use the syntax
```
(<list of options that shouldn't be suggested if OPTION is typed>)<OPTION to be suggested>[<OPTION description>]
```
That's why I've posifxed `--help` inside every parenthesis and added all options to the `--help` line.

**Comment by rodrigosiqueira** [comment]
@GuilhermeMoreno any update here?

**Comment by rodrigosiqueira** [comment]
Closed due to the lack of reply.

**Pull request closed without merging**
