### PR TITLE
src: autocomplete: add remaining fish completions

### PR DESCRIPTION
**Pull request by lucasoshiro**
In this PR I made the remaining completions. As far as I'm concerned, with this PR `kw` will be totally compatible with `fish`.

Here is a screenshot of a completion for a subcommand:
image

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
Hi @lucasoshiro , thank you for this patch! Really nice job here :)

I found the following error after execute `./run_tests.sh`:

```bash
ASSERT:Fish suggestions for 'kw ssh ' aren't the expected:\n1c1,23
...
ASSERT:Fish suggestions for 'kw s ' aren't the expected:\n1c1,24
```

Could you check it?

Finally, update your branch with the current version of "unstable" branch.

**Comment by rodrigosiqueira** [comment]
@lucasoshiro do you have plans to finish this? Just let me know, otherwise I'll close it.

Thanks

**Comment by lucasoshiro** [comment]
@rodrigosiqueira You can close it by now. I have plans to finish it in the future, but I can send it in other PR. Thanks!

**Comment by rodrigosiqueira** [comment]
@lucasoshiro thank you very much in your effort for making` kw` work with fish, this sort of work adds a lot of value to our project. I hope I can see you around :)

**Pull request closed without merging**
