### PR TITLE
src: _kw: Add Zsh completion for `kw build` `--full-cleanup` option

### PR DESCRIPTION
**Pull request by davidbtadokoro**
Add Zsh completion for the `--full-cleanup` option of the `kw build` feature.

### CODE REVIEW

**Comment by davidbtadokoro** [comment]
@aquilamacedo I assumed that `--full-cleanup` should be mutually excludent to all other options besides `--verbose`, in other words, when using `--full-cleanup` no other option should be displayed aside from `--verbose`.

Is this correct? And if so, can you check if this PR adds this behaviour correctly?

**Comment by davidbtadokoro** [comment]
Thanks for the change! Merged into the unstable.

**Comment by rodrigosiqueira** [comment]
@davidbtadokoro feel free to merge this change in the unstable branch.

**Comment by davidbtadokoro** [comment]
After feedback approving the behaviour from @aquilamacedo, I merged it on unstable.

**Pull request closed without merging**
