### PR TITLE
[README] Suggest new contributors to look for new issues that aren't done

### PR DESCRIPTION
**Pull request by AbhinavMir**
Currently the suggestion is to suggest new contributors to look for "good first issues", however some of those issues have potential stable branch candidates that are added to unstable branch as of now. Just modifying old Readme to point to [good first issues with no candidates](https://github.com/kworkflow/kworkflow/issues?q=is%3Aopen+label%3A%22good+first+issue%22+-label%3A%22done%3A+wait+for+stable%22).

Trivial, but something I came across right now. I love the labeling system by the way, and hope more projects use this!

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
Hi @AbhinavMir ,
First of all, thanks a lot for your PR.
Overall, it looks good, but you must update your commit message. Since you changed the README file, use the prefix README:. Also, add a proper commit description similar to what you said in the PR message.

**Comment by AbhinavMir** [comment]
@rodrigosiqueira Thanks! I'm moving right now so will do it in a bit, but would you rather have one commit for a cleaner commit history? If so I'll squash them together.

**Comment by rodrigosiqueira** [comment]
yes, squash them together.

**Comment by rodrigosiqueira** [comment]
Hi @AbhinavMir, I closed this PR since it has not been updated in a long time. Feel free to open a new PR with an improved version.
Thanks

**Pull request closed without merging**
