### PR TITLE
Improve readability integrations utils

### PR DESCRIPTION
**Pull request by jppaulo06**
This pull request introduces minor changes to the integration tests code with the primary goal of improving code readability. The modifications do not alter the behavior or fix errors of the tests but focus on enhancing the clarity and maintainability of the code.

Key improvements include:
- Refactoring certain sections of the code to adhere to already used coding conventions.
- Adjusting variable names for better descriptive clarity.
- Reordering lines or sections to improve the logical flow of the code.

In addition to these changes, the PR slightly modifies the messages outputted during integration tests.

### CODE REVIEW

**Review by davidbtadokoro — CHANGES_REQUESTED** [review]
Thanks so much for the changes @jppaulo06! Refactoring are just as important as the ones about behavior and stuff :smiley:

Tested and it seems to not alter any behavior. Left some simple comments, so see if you can address them. Feel free to ping me for any doubt.

**Comment by rodrigosiqueira** [comment]
Hi @jppaulo06 , any update here?

**Comment by jppaulo06** [comment]
Sorry for the delay, being busy with some other projects in the last days :(

**Comment by davidbtadokoro** [comment]
Hey @jppaulo06, thanks for the update! Great refactoring all around! Merged into the unstable branch :+1:

**Pull request closed without merging**
