### PR TITLE
Update contributor's guide URL

### PR DESCRIPTION
**Pull request by tales-aparecida**
Update contributor's guide URL in the README with the official kw domain

### CODE REVIEW

**Comment by andrealmeid** [comment]
Reviewed-by: André Almeida <andrealmeid@riseup.net>

**Comment by andrealmeid** [comment]
Reviewed-by: André Almeida <andrealmeid@riseup.net>

**Review by kwy95 — APPROVED** [review]
LGTM

**Comment by rodrigosiqueira** [comment]
Merged! Thanks

**Pull request closed without merging**
