### PR TITLE
src: device_info: Expand kw device info

### LINKED ISSUE #951: Expand kw device info
**Description:**

Expand kw device to provide the following information:

1. Display info (name, port, number of displays, etc).
2. Kernel version.

**Why:**

This information can be helpful for people who report bugs in some platforms.

### PR DESCRIPTION
**Pull request by gustavohenriquesr**
Add more information to the `kw device` command. This information seems to be useful for people to debug and makes the device description more complete. Kernel descriptions such as name, version and release have been added. Also, display information (such as name, number of active displays and resolution) has been provided. Finally, information about the CPU architecture has also been added.

Co-author: @brunaafl

Resolves #951

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
@gustavohenriquesr , please make your changes using the unstable branch.

https://kworkflow.org/content/howtocontribute.html

**Comment by gustavohenriquesr** [comment]
Hi @rodrigosiqueira, I worked based on unstable branch, as recommended. I accidentally sync with stable and I fixed the error immediately. There's no changes but the suggestions for PR. Nevertheless, I will create other PR about the same topic.

**Comment by rodrigosiqueira** [comment]
This PR has 20 commits (check the commit tab). You don't need to create a new PR; just use push force on your branch after you fix the issue.

**Comment by gustavohenriquesr** [comment]
@rodrigosiqueira I had a problem with my local repo, so I decided to create a new [PR](kworkflow/kworkflow/pull/1107)

**Pull request closed without merging**
